---
- name: Update and Upgrade Packages
  hosts: client  # Replace 'client' with the actual hostname or group name from your inventory
  become: yes    # Use privilege escalation (sudo) to run the tasks

  tasks:
    - name: Update package cache
      apt:
        update_cache: yes

    - name: Upgrade packages
      apt:
        upgrade: yes
        autoremove: yes
        autoclean: yes


